blank_issues_enabled: true
contact_links:
  - name: Questions and ideas
    url: https://github.com/shipshitshow/premiere/discussions
    about: Use GitHub Discussions for general questions and brainstorming.
